apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-validator-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "5"
spec:
  rules:
    - host: validator.payflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transaction-validator
                port:
                  number: 80
