apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-validator
spec:
  ingressClassName: nginx
  rules:
    - host: validator.payflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transaction-validator
                port:
                  number: 80
