apiVersion: v1
kind: Service
metadata:
  name: transaction-validator-canary
  labels:
    app: transaction-validator-canary
spec:
  type: ClusterIP
  selector:
    app: transaction-validator-canary
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
