global:
  scrape_interval: 15s

scrape_configs:
  - job_name: transaction-validator
    metrics_path: /metrics
    static_configs:
      - targets: ['transaction-validator:8080']
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
